default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-54-221-198-156.compute-1.amazonaws.com
  database: d1n1lsql1hk86p
  username: wuwhwxvzewrxnq
  password: 38c53faa7bc276d55eb2bfda8a6bd7d32ed1dff11469f90771d6e66b9d646756
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

production:
  <<: *default
